FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install xmltodict
RUN pip install --no-cache-dir -r requirements.txt

RUN pip install pylint

COPY . .

ENTRYPOINT ["pylint", "--max-line-length=140","--fail-under=8"]
