name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Lint
    - uses: ricardochaves/python-lint@v1.4.0
      with:
        python-root-list: "main.py"
        use-pylint: true
        use-pycodestyle: false
        use-flake8: false
        use-black: false
        use-mypy: false
        use-isort: false
        extra-pylint-options: "--max-line-length=140"
        extra-pycodestyle-options: ""
        extra-flake8-options: ""
        extra-black-options: ""
        extra-mypy-options: ""
        extra-isort-options: ""

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Build and push Docker image
      run: |
        docker build \
          --build-arg BGG_API_URL=${{ secrets.BGG_API_URL }} \
          --build-arg BGG_API_ENDPOINT_BOARDGAME=${{ secrets.BGG_API_ENDPOINT_BOARDGAME }} \
          --build-arg GATHERING_API_URL=${{ secrets.GATHERING_API_URL }} \
          --build-arg GATHERING_API_URL_NODATA=${{ secrets.GATHERING_API_URL_NODATA }} \
          --build-arg PRICE_LOOKUP_URL=${{ secrets.PRICE_LOOKUP_URL }} \
          --build-arg LOG_DESTINATION=${{ secrets.LOG_DESTINATION }} \
          -t ghcr.io/${{ github.repository_owner }}/gathering-game-service:main .
        docker push ghcr.io/${{ github.repository_owner }}/gathering-game-service:main