name: Build and Push

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Build the Docker image
      if: ${{ github.event.pull_request.merged }}
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
