name: Run Tests

on:
  push:
    branches-ignore:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker image for pytest
      run: docker build -f Dockerfile.pytest -t pytest-container .

    - name: Run pytest inside container with arguments
      run: docker run pytest-container /app/tests -vvv